server.port=8080

# Oracle XE/19c con SID = orcl  (no service name)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orclpdb
spring.datasource.username=proyectoFinal
spring.datasource.password=admin123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hikari
spring.datasource.hikari.maximum-pool-size=5

# JPA: solo usamos JdbcTemplate, no Hibernate DDL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.default_schema=PROYECTOFINAL

# Schema target para los GRANT/REVOKE de la demo (rúbrica)
app.target.schema=HR

# JWT
app.jwt.secret=CAMBIA_ESTA_CLAVE_SUPER_LARGA_DE_MINIMO_32_CARACTERES_123456
app.jwt.expiration-ms=86400000
