server.port=8080
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl
spring.datasource.username=c##adminProyectoFinal
spring.datasource.password=admin123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

app.jwt.secret=CAMBIA_ESTA_CLAVE_SUPER_LARGA_DE_MINIMO_32_CARACTERES_123456
app.jwt.expiration-ms=86400000