CREATE USER c##adminProyectoFinal IDENTIFIED BY "admin123";
----PERMISOS USUARIO PARA PROYECTO DB2:
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE TRIGGER TO c##adminProyectoFinal;
ALTER USER c##adminProyectoFinal QUOTA UNLIMITED ON USERS;