-- ============================================================
--  DCL MANAGER - Esquema completo Oracle
--  Proyecto: Bases de Datos II
--  Módulos:
--    1. Usuarios de la Aplicación
--    2. Roles y Jerarquía
--    3. Permisos / Privilegios
--    4. Relaciones (Asignación)
--    5. Auditoría y Scripts SQL
--    6. Secuencias
--    7. Triggers de Auditoría
--    8. Vistas de Soporte
-- ============================================================


-- ============================================================
--  MÓDULO 0 — Limpieza previa (ejecutar si se reinicia el esquema)
-- ============================================================
-- Descomenta este bloque sólo si necesitas resetear todo:
/*
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN (
              'SQL_SCRIPTS','AUDIT_LOG','USER_PERMISSIONS',
              'ROLE_PERMISSIONS','USER_ROLES',
              'APP_PERMISSIONS','APP_ROLES','APP_USERS'
            )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
  FOR s IN (SELECT sequence_name FROM user_sequences
            WHERE sequence_name LIKE 'SEQ_%') LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/
*/


-- ============================================================
--  MÓDULO 1 — Usuarios de la Aplicación
-- ============================================================
--  Almacena los administradores que usan la herramienta web.
--  NO son usuarios Oracle; la app se conecta a Oracle con un
--  único usuario de servicio y ejecuta los DCL desde el backend.
-- ============================================================

CREATE TABLE APP_USERS (
    user_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50)    NOT NULL,
    password_hash   VARCHAR2(255)   NOT NULL,   -- bcrypt / SHA-256 desde el backend
    email           VARCHAR2(100)   NOT NULL,
    full_name       VARCHAR2(150)   NOT NULL,
    status          VARCHAR2(20)    DEFAULT 'ACTIVO'
                        CONSTRAINT ck_users_status
                        CHECK (status IN ('ACTIVO','INACTIVO','BLOQUEADO')),
    app_role        VARCHAR2(20)    DEFAULT 'VIEWER'
                        CONSTRAINT ck_users_approle
                        CHECK (app_role IN ('SUPERADMIN','ADMIN','VIEWER')),
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    last_login      TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);

ALTER TABLE APP_USERS ADD oracle_username VARCHAR2(128);

COMMENT ON TABLE  APP_USERS              IS 'Administradores de la herramienta DCL Manager';
COMMENT ON COLUMN APP_USERS.app_role     IS 'SUPERADMIN: todo | ADMIN: gestión | VIEWER: solo lectura';
COMMENT ON COLUMN APP_USERS.status       IS 'ACTIVO | INACTIVO | BLOQUEADO';
COMMENT ON COLUMN APP_USERS.password_hash IS 'Hash generado en el backend; nunca contraseña en claro';


-- ============================================================
--  MÓDULO 2 — Roles y Jerarquía
-- ============================================================
--  Modela los roles Oracle (CREATE ROLE) y su herencia.
--  parent_role_id = NULL indica rol raíz (sin herencia).
-- ============================================================

CREATE TABLE APP_ROLES (
    role_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR2(100)   NOT NULL,
    description     VARCHAR2(500),
    parent_role_id  NUMBER,                     -- auto-referencia para herencia
    is_oracle_role  CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_roles_isoracle
                        CHECK (is_oracle_role IN ('S','N')),
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      NUMBER,
    CONSTRAINT uq_roles_name    UNIQUE (role_name),
    CONSTRAINT fk_roles_parent  FOREIGN KEY (parent_role_id)
        REFERENCES APP_ROLES (role_id),
    CONSTRAINT fk_roles_creator FOREIGN KEY (created_by)
        REFERENCES APP_USERS (user_id)
);

COMMENT ON TABLE  APP_ROLES               IS 'Roles Oracle gestionados por la aplicación';
COMMENT ON COLUMN APP_ROLES.parent_role_id IS 'FK recursiva: rol padre en la jerarquía';
COMMENT ON COLUMN APP_ROLES.is_oracle_role IS 'S = ya existe en Oracle; N = pendiente de aplicar';


-- ============================================================
--  MÓDULO 3 — Permisos / Privilegios
-- ============================================================
--  Catálogo de los privilegios disponibles.
--  Representa los objetos sobre los que se puede hacer GRANT.
-- ============================================================

CREATE TABLE APP_PERMISSIONS (
    permission_id   NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name     VARCHAR2(128)   NOT NULL,   -- nombre de tabla, vista, proc, etc.
    object_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_perms_objtype
                        CHECK (object_type IN (
                            'TABLE','VIEW','SEQUENCE','PROCEDURE',
                            'FUNCTION','PACKAGE','SCHEMA','SYSTEM')),
    privilege_type  VARCHAR2(50)    NOT NULL,   -- SELECT, INSERT, EXECUTE, etc.
    schema_name     VARCHAR2(128)   NOT NULL,   -- propietario del objeto en Oracle
    description     VARCHAR2(300),
    CONSTRAINT uq_perms_combo UNIQUE (schema_name, object_name, privilege_type)
);

COMMENT ON TABLE  APP_PERMISSIONS              IS 'Catálogo de privilegios disponibles para asignar';
COMMENT ON COLUMN APP_PERMISSIONS.object_type  IS 'Tipo de objeto Oracle';
COMMENT ON COLUMN APP_PERMISSIONS.privilege_type IS 'SELECT | INSERT | UPDATE | DELETE | EXECUTE | ALL';
COMMENT ON COLUMN APP_PERMISSIONS.schema_name   IS 'Esquema Oracle dueño del objeto';


-- ============================================================
--  MÓDULO 4 — Relaciones de Asignación
-- ============================================================
--  4A: Roles asignados a usuarios de la app
--  4B: Permisos asignados a roles
--  4C: Permisos directos asignados a usuarios
-- ============================================================

-- 4A — Roles asignados a usuarios de la aplicación
CREATE TABLE USER_ROLES (
    user_id         NUMBER          NOT NULL,
    role_id         NUMBER          NOT NULL,
    assigned_at     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    assigned_by     NUMBER          NOT NULL,   -- quién hizo la asignación
    expires_at      TIMESTAMP,                  -- NULL = sin expiración
    is_active       CHAR(1)         DEFAULT 'S'
                        CONSTRAINT ck_ur_active
                        CHECK (is_active IN ('S','N')),
    CONSTRAINT pk_user_roles    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user       FOREIGN KEY (user_id)
        REFERENCES APP_USERS (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role       FOREIGN KEY (role_id)
        REFERENCES APP_ROLES (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_assignedby FOREIGN KEY (assigned_by)
        REFERENCES APP_USERS (user_id)
);

COMMENT ON TABLE USER_ROLES IS 'Asignación de roles a usuarios de la aplicación';


-- 4B — Permisos asignados a roles (GRANT <priv> ON <obj> TO <role>)
CREATE TABLE ROLE_PERMISSIONS (
    role_id         NUMBER          NOT NULL,
    permission_id   NUMBER          NOT NULL,
    grant_option    CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_rp_grantoption
                        CHECK (grant_option IN ('S','N')),  -- WITH GRANT OPTION
    granted_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    granted_by      NUMBER          NOT NULL,
    CONSTRAINT pk_role_permissions  PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role           FOREIGN KEY (role_id)
        REFERENCES APP_ROLES (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission     FOREIGN KEY (permission_id)
        REFERENCES APP_PERMISSIONS (permission_id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_grantedby      FOREIGN KEY (granted_by)
        REFERENCES APP_USERS (user_id)
);

COMMENT ON TABLE  ROLE_PERMISSIONS             IS 'Permisos asignados a roles (genera GRANT ... TO role)';
COMMENT ON COLUMN ROLE_PERMISSIONS.grant_option IS 'S = WITH GRANT OPTION en el SQL generado';


-- 4C — Permisos directos a usuarios (GRANT <priv> ON <obj> TO <oracle_user>)
CREATE TABLE USER_PERMISSIONS (
    user_id         NUMBER          NOT NULL,
    permission_id   NUMBER          NOT NULL,
    grant_option    CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_up_grantoption
                        CHECK (grant_option IN ('S','N')),
    granted_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    granted_by      NUMBER          NOT NULL,
    oracle_username VARCHAR2(128)   NOT NULL,   -- usuario Oracle destino del GRANT
    CONSTRAINT pk_user_permissions  PRIMARY KEY (user_id, permission_id),
    CONSTRAINT fk_up_user           FOREIGN KEY (user_id)
        REFERENCES APP_USERS (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_up_permission     FOREIGN KEY (permission_id)
        REFERENCES APP_PERMISSIONS (permission_id) ON DELETE CASCADE,
    CONSTRAINT fk_up_grantedby      FOREIGN KEY (granted_by)
        REFERENCES APP_USERS (user_id)
);

COMMENT ON TABLE  USER_PERMISSIONS              IS 'Permisos directos a usuarios Oracle (sin pasar por rol)';
COMMENT ON COLUMN USER_PERMISSIONS.oracle_username IS 'Usuario Oracle destino (puede diferir del username de la app)';


-- ============================================================
--  MÓDULO 5 — Auditoría y Scripts SQL Generados
-- ============================================================

-- 5A — Log de auditoría de cada acción administrativa
CREATE TABLE AUDIT_LOG (
    log_id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id   NUMBER          NOT NULL,   -- quién ejecutó la acción
    action_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_audit_action
                        CHECK (action_type IN (
                            'GRANT','REVOKE','CREATE_ROLE','DROP_ROLE',
                            'CREATE_USER','DROP_USER','MODIFY_USER',
                            'ASSIGN_ROLE','REVOKE_ROLE','LOGIN','LOGIN_FAILED')),
    target_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_audit_target
                        CHECK (target_type IN (
                            'USER','ROLE','PERMISSION','SYSTEM')),
    target_id       NUMBER,                     -- ID del registro afectado
    target_name     VARCHAR2(255),              -- nombre legible del objetivo
    sql_generated   CLOB,                       -- SQL DCL que se produjo
    performed_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address      VARCHAR2(45),               -- IPv4 o IPv6
    result          VARCHAR2(10)    DEFAULT 'OK'
                        CONSTRAINT ck_audit_result
                        CHECK (result IN ('OK','ERROR')),
    error_detail    VARCHAR2(1000),             -- mensaje de error si result = ERROR
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id)
        REFERENCES APP_USERS (user_id)
);

COMMENT ON TABLE  AUDIT_LOG             IS 'Registro inmutable de todas las acciones administrativas';
COMMENT ON COLUMN AUDIT_LOG.sql_generated IS 'SQL DCL exacto que se generó y/o ejecutó';
COMMENT ON COLUMN AUDIT_LOG.result       IS 'OK = exitoso | ERROR = falló (ver error_detail)';


-- 5B — Scripts SQL generados automáticamente para aplicar en Oracle
CREATE TABLE SQL_SCRIPTS (
    script_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_by    NUMBER          NOT NULL,
    script_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_scripts_type
                        CHECK (script_type IN (
                            'GRANT','REVOKE','CREATE_ROLE',
                            'DROP_ROLE','MIXED')),
    script_content  CLOB            NOT NULL,   -- bloque SQL completo listo para ejecutar
    description     VARCHAR2(500),
    generated_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    applied         CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_scripts_applied
                        CHECK (applied IN ('S','N')),
    applied_at      TIMESTAMP,
    applied_by      NUMBER,
    CONSTRAINT fk_scripts_generatedby FOREIGN KEY (generated_by)
        REFERENCES APP_USERS (user_id),
    CONSTRAINT fk_scripts_appliedby   FOREIGN KEY (applied_by)
        REFERENCES APP_USERS (user_id)
);

COMMENT ON TABLE  SQL_SCRIPTS               IS 'Scripts DCL generados por la aplicación para ejecutar en Oracle';
COMMENT ON COLUMN SQL_SCRIPTS.script_content IS 'SQL completo: puede contener múltiples sentencias DCL';
COMMENT ON COLUMN SQL_SCRIPTS.applied        IS 'S = ya aplicado en Oracle; N = pendiente';


-- ============================================================
--  MÓDULO 6 — Índices de rendimiento
-- ============================================================

CREATE INDEX idx_audit_actor    ON AUDIT_LOG     (actor_user_id, performed_at DESC);
CREATE INDEX idx_audit_target   ON AUDIT_LOG     (target_type, target_id);
CREATE INDEX idx_audit_date     ON AUDIT_LOG     (performed_at DESC);
CREATE INDEX idx_ur_role        ON USER_ROLES    (role_id);
CREATE INDEX idx_rp_perm        ON ROLE_PERMISSIONS (permission_id);
CREATE INDEX idx_up_oracle_user ON USER_PERMISSIONS (oracle_username);
CREATE INDEX idx_scripts_date   ON SQL_SCRIPTS   (generated_at DESC);
CREATE INDEX idx_scripts_pending ON SQL_SCRIPTS (applied);   -- índice parcial: sólo pendientes


-- ============================================================
--  MÓDULO 7 — Triggers de Auditoría Automática
-- ============================================================

-- 7A: Registro automático de cambios en APP_USERS
CREATE OR REPLACE TRIGGER trg_audit_app_users
    AFTER INSERT OR UPDATE OR DELETE ON APP_USERS
    FOR EACH ROW
DECLARE
    v_action    VARCHAR2(30);
    v_target    VARCHAR2(255);
BEGIN
    IF INSERTING THEN
        v_action := 'CREATE_USER';
        v_target := :NEW.username;
    ELSIF UPDATING THEN
        v_action := 'MODIFY_USER';
        v_target := :NEW.username;
    ELSE
        v_action := 'DROP_USER';
        v_target := :OLD.username;
    END IF;

    INSERT INTO AUDIT_LOG (
        actor_user_id, action_type, target_type,
        target_id, target_name, performed_at, result
    ) VALUES (
        NVL(:NEW.user_id, :OLD.user_id),
        v_action, 'USER',
        NVL(:NEW.user_id, :OLD.user_id),
        v_target, SYSTIMESTAMP, 'OK'
    );
END;
/

-- 7B: Registro automático de cambios en APP_ROLES
CREATE OR REPLACE TRIGGER trg_audit_app_roles
    AFTER INSERT OR DELETE ON APP_ROLES
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(30);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'CREATE_ROLE' ELSE 'DROP_ROLE' END;

    INSERT INTO AUDIT_LOG (
        actor_user_id, action_type, target_type,
        target_id, target_name, performed_at, result
    ) VALUES (
        NVL(:NEW.created_by, :OLD.created_by),
        v_action, 'ROLE',
        NVL(:NEW.role_id, :OLD.role_id),
        NVL(:NEW.role_name, :OLD.role_name),
        SYSTIMESTAMP, 'OK'
    );
END;
/

-- 7C: Registro de asignación / revocación de roles a usuarios
CREATE OR REPLACE TRIGGER trg_audit_user_roles
    AFTER INSERT OR DELETE ON USER_ROLES
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(30);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'ASSIGN_ROLE' ELSE 'REVOKE_ROLE' END;

    INSERT INTO AUDIT_LOG (
        actor_user_id, action_type, target_type,
        target_id, target_name, performed_at, result
    ) VALUES (
        NVL(:NEW.assigned_by, :OLD.assigned_by),
        v_action, 'ROLE',
        NVL(:NEW.role_id, :OLD.role_id),
        'USER_ID=' || NVL(:NEW.user_id, :OLD.user_id) ||
            ' ROLE_ID=' || NVL(:NEW.role_id, :OLD.role_id),
        SYSTIMESTAMP, 'OK'
    );
END;
/


-- ============================================================
--  MÓDULO 8 — Vistas de Soporte para el Backend
-- ============================================================

-- Vista completa de permisos efectivos por usuario
--   (permisos directos + permisos heredados via roles)
CREATE OR REPLACE VIEW VW_USER_EFFECTIVE_PERMISSIONS AS
SELECT
    u.user_id,
    u.username,
    u.oracle_username,
    p.schema_name,
    p.object_name,
    p.object_type,
    p.privilege_type,
    up.grant_option,
    'DIRECTO' AS origin_type,
    NULL       AS via_role_name
FROM APP_USERS u
JOIN USER_PERMISSIONS up ON up.user_id = u.user_id
JOIN APP_PERMISSIONS  p  ON p.permission_id = up.permission_id

UNION ALL

SELECT
    u.user_id,
    u.username,
    u.oracle_username,
    p.schema_name,
    p.object_name,
    p.object_type,
    p.privilege_type,
    rp.grant_option,
    'ROL'      AS origin_type,
    r.role_name AS via_role_name
FROM APP_USERS u
JOIN USER_ROLES      ur ON ur.user_id = u.user_id AND ur.is_active = 'S'
JOIN APP_ROLES       r  ON r.role_id  = ur.role_id
JOIN ROLE_PERMISSIONS rp ON rp.role_id = r.role_id
JOIN APP_PERMISSIONS  p  ON p.permission_id = rp.permission_id;

COMMENT ON TABLE VW_USER_EFFECTIVE_PERMISSIONS IS
    'Permisos efectivos de cada usuario: directos + heredados por rol';


-- Vista de jerarquía de roles (nivel de anidamiento)
CREATE OR REPLACE VIEW VW_ROLE_HIERARCHY AS
SELECT
    r.role_id,
    r.role_name,
    r.parent_role_id,
    p.role_name  AS parent_role_name,
    r.is_oracle_role,
    r.description
FROM APP_ROLES r
LEFT JOIN APP_ROLES p ON p.role_id = r.parent_role_id;

COMMENT ON TABLE VW_ROLE_HIERARCHY IS 'Árbol de herencia de roles con nombre del padre';


-- Vista de auditoría enriquecida (join con username legible)
CREATE OR REPLACE VIEW VW_AUDIT_LOG AS
SELECT
    a.log_id,
    u.username      AS actor_username,
    a.action_type,
    a.target_type,
    a.target_name,
    a.result,
    a.error_detail,
    a.ip_address,
    a.performed_at,
    a.sql_generated
FROM AUDIT_LOG a
JOIN APP_USERS u ON u.user_id = a.actor_user_id
ORDER BY a.performed_at DESC;

COMMENT ON TABLE VW_AUDIT_LOG IS 'Log de auditoría con nombre de usuario legible';


-- Vista de scripts pendientes de aplicar
CREATE OR REPLACE VIEW VW_PENDING_SCRIPTS AS
SELECT
    s.script_id,
    u.username  AS generated_by_username,
    s.script_type,
    s.description,
    s.generated_at,
    s.script_content
FROM SQL_SCRIPTS s
JOIN APP_USERS u ON u.user_id = s.generated_by
WHERE s.applied = 'N'
ORDER BY s.generated_at;

COMMENT ON TABLE VW_PENDING_SCRIPTS IS 'Scripts DCL generados que aún no han sido aplicados en Oracle';


-- ============================================================
--  MÓDULO 9 — Datos iniciales (SEED)
-- ============================================================

-- Usuario superadmin por defecto
INSERT INTO APP_USERS (username, password_hash, email, full_name, app_role, status)
VALUES (
    'superadmin',
    '$2b$12$CHANGE_THIS_HASH_IN_PRODUCTION',   -- reemplazar con hash real
    'admin@dcl-manager.local',
    'Administrador Principal',
    'SUPERADMIN',
    'ACTIVO'
);

-- Rol raíz de ejemplo
INSERT INTO APP_ROLES (role_name, description, parent_role_id, is_oracle_role, created_by)
VALUES (
    'DBA_MASTER',
    'Rol raíz con todos los privilegios del sistema',
    NULL,
    'N',
    1
);

-- Rol hijo de ejemplo
INSERT INTO APP_ROLES (role_name, description, parent_role_id, is_oracle_role, created_by)
VALUES (
    'APP_READ_ONLY',
    'Acceso de sólo lectura a tablas de la aplicación',
    1,
    'N',
    1
);

-- Permiso de ejemplo: SELECT sobre la tabla APP_USERS
INSERT INTO APP_PERMISSIONS (object_name, object_type, privilege_type, schema_name, description)
VALUES (
    'APP_USERS',
    'TABLE',
    'SELECT',
    'APP_ADMIN',
    'Lectura de la tabla de usuarios de la aplicación'
);

COMMIT;


-- ============================================================
--  FIN DEL SCRIPT
--  Objetos creados:
--    Tablas (8): APP_USERS, APP_ROLES, APP_PERMISSIONS,
--                USER_ROLES, ROLE_PERMISSIONS, USER_PERMISSIONS,
--                AUDIT_LOG, SQL_SCRIPTS
--    Índices  (8)
--    Triggers (3): trg_audit_app_users, trg_audit_app_roles,
--                  trg_audit_user_roles
--    Vistas   (4): VW_USER_EFFECTIVE_PERMISSIONS,
--                  VW_ROLE_HIERARCHY, VW_AUDIT_LOG,
--                  VW_PENDING_SCRIPTS
-- ============================================================