-- ============================================================
--  DCL MANAGER - Esquema completo Oracle
--  Proyecto: Bases de Datos II
--
--  Ejecutar conectado como proyectoFinal:
--     sqlplus proyectoFinal/admin123@localhost:1521/ORCLPDB
--
--  Módulos:
--    1. Usuarios de la Aplicación (administradores del tool)
--    2. Roles y Jerarquía
--    3. Permisos / Privilegios
--    4. Relaciones (Asignación)
--    5. Auditoría y Scripts SQL
--    6. Índices
--    7. Triggers de Auditoría
--    8. Vistas de Soporte
--
--  NOTA: el seed del usuario superadmin lo crea el backend
--  al arrancar (BootstrapService) con un hash bcrypt real,
--  para evitar problemas de escape al insertar el hash en SQL.
-- ============================================================


-- ============================================================
--  MÓDULO 0 — Limpieza previa (descomenta si reinicias)
-- ============================================================
/*
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN (
              'SQL_SCRIPTS','AUDIT_LOG','USER_PERMISSIONS',
              'ROLE_PERMISSIONS','USER_ROLES',
              'APP_PERMISSIONS','APP_ROLES','APP_USERS'
            )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/
*/


-- ============================================================
--  MÓDULO 1 — Usuarios de la Aplicación
-- ============================================================

CREATE TABLE APP_USERS (
    user_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50)    NOT NULL,
    password_hash   VARCHAR2(255)   NOT NULL,
    email           VARCHAR2(100)   NOT NULL,
    full_name       VARCHAR2(150)   NOT NULL,
    status          VARCHAR2(20)    DEFAULT 'ACTIVO'
                        CONSTRAINT ck_users_status
                        CHECK (status IN ('ACTIVO','INACTIVO','BLOQUEADO')),
    app_role        VARCHAR2(20)    DEFAULT 'VIEWER'
                        CONSTRAINT ck_users_approle
                        CHECK (app_role IN ('SUPERADMIN','ADMIN','VIEWER')),
    oracle_username VARCHAR2(128),
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    last_login      TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);


-- ============================================================
--  MÓDULO 2 — Roles y Jerarquía
-- ============================================================

CREATE TABLE APP_ROLES (
    role_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR2(100)   NOT NULL,
    description     VARCHAR2(500),
    parent_role_id  NUMBER,
    is_oracle_role  CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_roles_isoracle
                        CHECK (is_oracle_role IN ('S','N')),
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      NUMBER,
    CONSTRAINT uq_roles_name    UNIQUE (role_name),
    CONSTRAINT fk_roles_parent  FOREIGN KEY (parent_role_id)
        REFERENCES APP_ROLES (role_id),
    CONSTRAINT fk_roles_creator FOREIGN KEY (created_by)
        REFERENCES APP_USERS (user_id)
);


-- ============================================================
--  MÓDULO 3 — Permisos / Privilegios
-- ============================================================

CREATE TABLE APP_PERMISSIONS (
    permission_id   NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name     VARCHAR2(128)   NOT NULL,
    object_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_perms_objtype
                        CHECK (object_type IN (
                            'TABLE','VIEW','SEQUENCE','PROCEDURE',
                            'FUNCTION','PACKAGE','SCHEMA','SYSTEM')),
    privilege_type  VARCHAR2(50)    NOT NULL,
    schema_name     VARCHAR2(128)   NOT NULL,
    description     VARCHAR2(300),
    CONSTRAINT uq_perms_combo UNIQUE (schema_name, object_name, privilege_type)
);


-- ============================================================
--  MÓDULO 4 — Relaciones de Asignación
-- ============================================================

CREATE TABLE USER_ROLES (
    user_id         NUMBER          NOT NULL,
    role_id         NUMBER          NOT NULL,
    assigned_at     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    assigned_by     NUMBER          NOT NULL,
    expires_at      TIMESTAMP,
    is_active       CHAR(1)         DEFAULT 'S'
                        CONSTRAINT ck_ur_active
                        CHECK (is_active IN ('S','N')),
    CONSTRAINT pk_user_roles    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_user       FOREIGN KEY (user_id)
        REFERENCES APP_USERS (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role       FOREIGN KEY (role_id)
        REFERENCES APP_ROLES (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_assignedby FOREIGN KEY (assigned_by)
        REFERENCES APP_USERS (user_id)
);

CREATE TABLE ROLE_PERMISSIONS (
    role_id         NUMBER          NOT NULL,
    permission_id   NUMBER          NOT NULL,
    grant_option    CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_rp_grantoption
                        CHECK (grant_option IN ('S','N')),
    granted_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    granted_by      NUMBER          NOT NULL,
    CONSTRAINT pk_role_permissions  PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role           FOREIGN KEY (role_id)
        REFERENCES APP_ROLES (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission     FOREIGN KEY (permission_id)
        REFERENCES APP_PERMISSIONS (permission_id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_grantedby      FOREIGN KEY (granted_by)
        REFERENCES APP_USERS (user_id)
);

CREATE TABLE USER_PERMISSIONS (
    user_id         NUMBER          NOT NULL,
    permission_id   NUMBER          NOT NULL,
    grant_option    CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_up_grantoption
                        CHECK (grant_option IN ('S','N')),
    granted_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    granted_by      NUMBER          NOT NULL,
    oracle_username VARCHAR2(128)   NOT NULL,
    CONSTRAINT pk_user_permissions  PRIMARY KEY (user_id, permission_id),
    CONSTRAINT fk_up_user           FOREIGN KEY (user_id)
        REFERENCES APP_USERS (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_up_permission     FOREIGN KEY (permission_id)
        REFERENCES APP_PERMISSIONS (permission_id) ON DELETE CASCADE,
    CONSTRAINT fk_up_grantedby      FOREIGN KEY (granted_by)
        REFERENCES APP_USERS (user_id)
);


-- ============================================================
--  MÓDULO 5 — Auditoría y Scripts SQL Generados
-- ============================================================

CREATE TABLE AUDIT_LOG (
    log_id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id   NUMBER          NOT NULL,
    action_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_audit_action
                        CHECK (action_type IN (
                            'GRANT','REVOKE','CREATE_ROLE','DROP_ROLE',
                            'CREATE_USER','DROP_USER','MODIFY_USER',
                            'LOCK_USER','UNLOCK_USER','CHANGE_PASSWORD',
                            'ASSIGN_ROLE','REVOKE_ROLE',
                            'LOGIN','LOGOUT','LOGIN_FAILED','TEST_ACCESS')),
    target_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_audit_target
                        CHECK (target_type IN (
                            'USER','ROLE','PERMISSION','SYSTEM')),
    target_id       NUMBER,
    target_name     VARCHAR2(255),
    sql_generated   CLOB,
    performed_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address      VARCHAR2(45),
    result          VARCHAR2(10)    DEFAULT 'OK'
                        CONSTRAINT ck_audit_result
                        CHECK (result IN ('OK','ERROR')),
    error_detail    VARCHAR2(2000),
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id)
        REFERENCES APP_USERS (user_id)
);

CREATE TABLE SQL_SCRIPTS (
    script_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_by    NUMBER          NOT NULL,
    script_type     VARCHAR2(30)    NOT NULL
                        CONSTRAINT ck_scripts_type
                        CHECK (script_type IN (
                            'GRANT','REVOKE','CREATE_ROLE','DROP_ROLE',
                            'CREATE_USER','DROP_USER','ALTER_USER','MIXED')),
    script_content  CLOB            NOT NULL,
    description     VARCHAR2(500),
    generated_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    applied         CHAR(1)         DEFAULT 'N'
                        CONSTRAINT ck_scripts_applied
                        CHECK (applied IN ('S','N')),
    applied_at      TIMESTAMP,
    applied_by      NUMBER,
    CONSTRAINT fk_scripts_generatedby FOREIGN KEY (generated_by)
        REFERENCES APP_USERS (user_id),
    CONSTRAINT fk_scripts_appliedby   FOREIGN KEY (applied_by)
        REFERENCES APP_USERS (user_id)
);


-- ============================================================
--  MÓDULO 6 — Índices
-- ============================================================

CREATE INDEX idx_audit_actor     ON AUDIT_LOG        (actor_user_id, performed_at DESC);
CREATE INDEX idx_audit_target    ON AUDIT_LOG        (target_type, target_id);
CREATE INDEX idx_audit_date      ON AUDIT_LOG        (performed_at DESC);
CREATE INDEX idx_ur_role         ON USER_ROLES       (role_id);
CREATE INDEX idx_rp_perm         ON ROLE_PERMISSIONS (permission_id);
CREATE INDEX idx_up_oracle_user  ON USER_PERMISSIONS (oracle_username);
CREATE INDEX idx_scripts_date    ON SQL_SCRIPTS      (generated_at DESC);
CREATE INDEX idx_scripts_pending ON SQL_SCRIPTS      (applied);


-- ============================================================
--  MÓDULO 7 — Triggers de Auditoría Automática
-- ============================================================

CREATE OR REPLACE TRIGGER trg_audit_app_users
    AFTER INSERT OR UPDATE OR DELETE ON APP_USERS
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(30);
    v_target VARCHAR2(255);
BEGIN
    IF INSERTING THEN
        v_action := 'CREATE_USER';
        v_target := :NEW.username;
    ELSIF UPDATING THEN
        v_action := 'MODIFY_USER';
        v_target := :NEW.username;
    ELSE
        v_action := 'DROP_USER';
        v_target := :OLD.username;
    END IF;

    INSERT INTO AUDIT_LOG (
        actor_user_id, action_type, target_type,
        target_id, target_name, performed_at, result
    ) VALUES (
        NVL(:NEW.user_id, :OLD.user_id),
        v_action, 'USER',
        NVL(:NEW.user_id, :OLD.user_id),
        v_target, SYSTIMESTAMP, 'OK'
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_app_roles
    AFTER INSERT OR DELETE ON APP_ROLES
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(30);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'CREATE_ROLE' ELSE 'DROP_ROLE' END;

    INSERT INTO AUDIT_LOG (
        actor_user_id, action_type, target_type,
        target_id, target_name, performed_at, result
    ) VALUES (
        NVL(:NEW.created_by, :OLD.created_by),
        v_action, 'ROLE',
        NVL(:NEW.role_id, :OLD.role_id),
        NVL(:NEW.role_name, :OLD.role_name),
        SYSTIMESTAMP, 'OK'
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_user_roles
    AFTER INSERT OR DELETE ON USER_ROLES
    FOR EACH ROW
DECLARE
    v_action VARCHAR2(30);
BEGIN
    v_action := CASE WHEN INSERTING THEN 'ASSIGN_ROLE' ELSE 'REVOKE_ROLE' END;

    INSERT INTO AUDIT_LOG (
        actor_user_id, action_type, target_type,
        target_id, target_name, performed_at, result
    ) VALUES (
        NVL(:NEW.assigned_by, :OLD.assigned_by),
        v_action, 'ROLE',
        NVL(:NEW.role_id, :OLD.role_id),
        'USER_ID=' || NVL(:NEW.user_id, :OLD.user_id) ||
            ' ROLE_ID=' || NVL(:NEW.role_id, :OLD.role_id),
        SYSTIMESTAMP, 'OK'
    );
END;
/


-- ============================================================
--  MÓDULO 8 — Vistas de Soporte
-- ============================================================

CREATE OR REPLACE VIEW VW_USER_EFFECTIVE_PERMISSIONS AS
SELECT
    u.user_id, u.username, u.oracle_username,
    p.schema_name, p.object_name, p.object_type,
    p.privilege_type, up.grant_option,
    'DIRECTO' AS origin_type, NULL AS via_role_name
FROM APP_USERS u
JOIN USER_PERMISSIONS up ON up.user_id = u.user_id
JOIN APP_PERMISSIONS  p  ON p.permission_id = up.permission_id

UNION ALL

SELECT
    u.user_id, u.username, u.oracle_username,
    p.schema_name, p.object_name, p.object_type,
    p.privilege_type, rp.grant_option,
    'ROL' AS origin_type, r.role_name AS via_role_name
FROM APP_USERS u
JOIN USER_ROLES       ur ON ur.user_id = u.user_id AND ur.is_active = 'S'
JOIN APP_ROLES        r  ON r.role_id  = ur.role_id
JOIN ROLE_PERMISSIONS rp ON rp.role_id = r.role_id
JOIN APP_PERMISSIONS  p  ON p.permission_id = rp.permission_id;


CREATE OR REPLACE VIEW VW_ROLE_HIERARCHY AS
SELECT
    r.role_id, r.role_name, r.parent_role_id,
    p.role_name  AS parent_role_name,
    r.is_oracle_role, r.description
FROM APP_ROLES r
LEFT JOIN APP_ROLES p ON p.role_id = r.parent_role_id;


CREATE OR REPLACE VIEW VW_AUDIT_LOG AS
SELECT
    a.log_id, u.username AS actor_username,
    a.action_type, a.target_type, a.target_name,
    a.result, a.error_detail, a.ip_address,
    a.performed_at, a.sql_generated
FROM AUDIT_LOG a
JOIN APP_USERS u ON u.user_id = a.actor_user_id;


COMMIT;
